require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Reloads changed application code automatically while developing.
  config.enable_reloading = true

  # Keeps boot faster in development by not loading the whole app at startup.
  config.eager_load = false

  # Shows detailed error pages locally so bugs are easier to debug.
  config.consider_all_requests_local = true

  # Adds server timing information to development responses.
  config.server_timing = true

  # Enables or disables controller caching depending on whether rails dev:cache has been toggled.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Uses memory storage for cache data during local development.
  config.cache_store = :memory_store

  # Stores uploaded files locally while developing.
  config.active_storage.service = :local

  # Does not raise errors if development emails fail to send.
  config.action_mailer.raise_delivery_errors = false

  # Prevents mailer templates from being cached in development.
  config.action_mailer.perform_caching = false

  # Sets localhost as the base URL for generated mailer links.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Sends deprecation warnings to the Rails log.
  config.active_support.deprecation = :log

  # Raises an error in the browser when database migrations are pending.
  config.active_record.migration_error = :page_load

  # Shows where database queries came from in the Rails logs.
  config.active_record.verbose_query_logs = true

  # Adds runtime tags to SQL query logs.
  config.active_record.query_log_tags_enabled = true

  # Shows where background jobs were enqueued from.
  config.active_job.verbose_enqueue_logs = true

  # Shows where redirects were triggered from.
  config.action_dispatch.verbose_redirect_logs = true

  # Keeps asset requests from cluttering the development log.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Adds rendered view file names into the page source during development.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raises an error when before_action only/except options point to missing controller actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
